-- Construction Job Items for QBCore
-- Add these items to your qb-core/shared/items.lua file

-- Safety Equipment
['construction_helmet'] = {
    ['name'] = 'construction_helmet',
    ['label'] = 'Construction Helmet',
    ['weight'] = 500,
    ['type'] = 'item',
    ['image'] = 'construction_helmet.png',
    ['unique'] = false,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'Standard safety helmet for construction work'
},
['safety_vest'] = {
    ['name'] = 'safety_vest',
    ['label'] = 'Safety Vest',
    ['weight'] = 500,
    ['type'] = 'item',
    ['image'] = 'safety_vest.png',
    ['unique'] = false,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'High-visibility safety vest'
},
['work_gloves'] = {
    ['name'] = 'work_gloves',
    ['label'] = 'Work Gloves',
    ['weight'] = 200,
    ['type'] = 'item',
    ['image'] = 'work_gloves.png',
    ['unique'] = false,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'Protective gloves for construction work'
},
['safety_boots'] = {
    ['name'] = 'safety_boots',
    ['label'] = 'Safety Boots',
    ['weight'] = 700,
    ['type'] = 'item',
    ['image'] = 'safety_boots.png',
    ['unique'] = false,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'Steel-toed boots for construction work'
},

-- Tools
['hammer'] = {
    ['name'] = 'hammer',
    ['label'] = 'Hammer',
    ['weight'] = 1000,
    ['type'] = 'item',
    ['image'] = 'hammer.png',
    ['unique'] = true,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'Standard construction hammer',
    ['durability'] = 100,
},
['screwdriver_set'] = {
    ['name'] = 'screwdriver_set',
    ['label'] = 'Screwdriver Set',
    ['weight'] = 800,
    ['type'] = 'item',
    ['image'] = 'screwdriver_set.png',
    ['unique'] = true,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'A set of various screwdrivers',
    ['durability'] = 100,
},
['power_drill'] = {
    ['name'] = 'power_drill',
    ['label'] = 'Power Drill',
    ['weight'] = 1500,
    ['type'] = 'item',
    ['image'] = 'power_drill.png',
    ['unique'] = true,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'Electric drill for construction tasks',
    ['durability'] = 100,
},
['measuring_tape'] = {
    ['name'] = 'measuring_tape',
    ['label'] = 'Measuring Tape',
    ['weight'] = 300,
    ['type'] = 'item',
    ['image'] = 'measuring_tape.png',
    ['unique'] = true,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'For precise measurements',
    ['durability'] = 100,
},
['wrench_set'] = {
    ['name'] = 'wrench_set',
    ['label'] = 'Wrench Set',
    ['weight'] = 1200,
    ['type'] = 'item',
    ['image'] = 'wrench_set.png',
    ['unique'] = true,
    ['useable'] = true,
    ['shouldClose'] = true,
    ['combinable'] = nil,
    ['description'] = 'A set of various sized wrenches',
    ['durability'] = 100,
},

-- Materials
['cement_bag'] = {
    ['name'] = 'cement_bag',
    ['label'] = 'Cement Bag',
    ['weight'] = 2000,
    ['type'] = 'item',
    ['image'] = 'cement_bag.png',
    ['unique'] = false,
    ['useable'] = false,
    ['shouldClose'] = false,
    ['combinable'] = nil,
    ['description'] = 'A bag of cement for construction'
},
['lumber'] = {
    ['name'] = 'lumber',
    ['label'] = 'Lumber',
    ['weight'] = 1500,
    ['type'] = 'item',
    ['image'] = 'lumber.png',
    ['unique'] = false,
    ['useable'] = false,
    ['shouldClose'] = false,
    ['combinable'] = nil,
    ['description'] = 'Wood for construction projects'
},
['steel_beam'] = {
    ['name'] = 'steel_beam',
    ['label'] = 'Steel Beam',
    ['weight'] = 3000,
    ['type'] = 'item',
    ['image'] = 'steel_beam.png',
    ['unique'] = false,
    ['useable'] = false,
    ['shouldClose'] = false,
    ['combinable'] = nil,
    ['description'] = 'Heavy steel beam for construction'
},
['brick_pack'] = {
    ['name'] = 'brick_pack',
    ['label'] = 'Brick Pack',
    ['weight'] = 2500,
    ['type'] = 'item',
    ['image'] = 'brick_pack.png',
    ['unique'] = false,
    ['useable'] = false,
    ['shouldClose'] = false,
    ['combinable'] = nil,
    ['description'] = 'A pack of construction bricks'
},
['wire_bundle'] = {
    ['name'] = 'wire_bundle',
    ['label'] = 'Wire Bundle',
    ['weight'] = 800,
    ['type'] = 'item',
    ['image'] = 'wire_bundle.png',
    ['unique'] = false,
    ['useable'] = false,
    ['shouldClose'] = false,
    ['combinable'] = nil,
    ['description'] = 'Bundle of electrical wires'
} 